version: '3'

services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - custom_net

  discovery-server:
    build: 
      context: ./netflix-discovery-server/
      dockerfile: ./Dockerfile
    ports:
      - "8761:8761"
    networks:
      - custom_net

networks:
  custom_net:
    driver: bridge